---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dataservice-catalog-deployment.yaml
  - dataservice-catalog-service.yaml
images:
  - name: dataservice-catalog
    newName: ghcr.io/informasjonsforvaltning/dataservice-catalog
    newTag: $(GIT_COMMIT_SHA)
