---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dataservice-catalog-deployment.yaml
  - dataservice-catalog-service.yaml
images:
  - name: dataservice-catalog
    newName: eu.gcr.io/digdir-fdk-infra/dataservice-catalog
    newTag: $(GIT_COMMIT_SHA)
